import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "outline": "#8d90a0",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "inverse-primary": "#0053db",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-container-lowest": "#060e20",
        "secondary-fixed": "#acedff",
        "inverse-on-surface": "#283044",
        "on-tertiary": "#003824",
        "on-surface-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "inverse-surface": "#dae2fd",
        "on-secondary-container": "#00424e",
        "primary-container": "#2563eb",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#93000a",
        "tertiary-container": "#007d55",
        "surface-container-highest": "#2d3449",
        "secondary-container": "#03b5d3",
        "background": "#0b1326",
        "on-secondary-fixed": "#001f26",
        "on-error": "#690005",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#bdffdb",
        "on-secondary": "#003640",
        "primary": "#b4c5ff",
        "outline-variant": "#434655",
        "on-primary": "#002a78",
        "surface-dim": "#0b1326",
        "surface-container-low": "#131b2e",
        "surface": "#0b1326",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "tertiary-fixed": "#6ffbbe",
        "surface-bright": "#31394d",
        "secondary": "#4cd7f6",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#b4c5ff",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#4cd7f6",
      },
      spacing: {
        "section-gap": "120px",
        "container-max": "1440px",
        "unit": "4px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "base": "4px",
      },
      fontFamily: {
        "body-lg": ["var(--font-lexend)", "sans-serif"],
        "body-md": ["var(--font-lexend)", "sans-serif"],
        "display-xl": ["var(--font-lexend)", "sans-serif"],
        "label-caps": ["var(--font-lexend)", "sans-serif"],
        "headline-md": ["var(--font-lexend)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-lexend)", "sans-serif"],
        "label-code": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg": ["var(--font-lexend)", "sans-serif"],
        "title-md": ["var(--font-lexend)", "sans-serif"],
        "label-sm": ["var(--font-lexend)", "sans-serif"],
        "label-md": ["var(--font-lexend)", "sans-serif"],
        "headline-xl": ["var(--font-lexend)", "sans-serif"],
        "lexend": ["var(--font-lexend)", "sans-serif"],
        "inter": ["var(--font-inter)", "sans-serif"],
        "jetbrains": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-code": ["14px", { "lineHeight": "1.5", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}

export default config
